SDKROOT:
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk # [osx]

CONDA_BUILD_SYSROOT:
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk # [osx]

CC:
  - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang # [osx]
CXX:
  - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ # [osx]
#CC:
#  - $BUILD_PREFIX/bin/clang # [osx and not arm64]
#CXX:
#  - $BUILD_PREFIX/bin/clang++ # [osx and not arm64]

numpy:
  - 1.26.2

MACOSX_DEPLOYMENT_TARGET:
  - 11.0 # [osx and not arm64]
  - 11.0 # [osx and arm64]
  #- 10.15 # [osx and not arm64]

c_compiler:
  - vs2019 # [win]
cxx_compiler:
  - vs2019 # [win]
cxx_compiler_version:
  - 11 # [linux]
c_compiler_version:
  - 11 # [linux]

pin_run_as_build:
  python:
    min_pin: x.x.x
    max_pin: x.x.x
  ffmpeg:
    min_pin: x.x.x
    max_pin: x.x.x
    
channel_sources:
  - conda-forge # [arm64]
  - pytorch
  - nvidia # [win or linux]
  - defaults # [not arm64]
