SDKROOT:
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk # [osx]

CONDA_BUILD_SYSROOT:
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk # [osx]

CC:
  - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang # [osx]
CXX:
  - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ # [osx]
#CC:
#  - $BUILD_PREFIX/bin/clang # [osx and not arm64]
#CXX:
#  - $BUILD_PREFIX/bin/clang++ # [osx and not arm64]

numpy:
  - 2 # [not osx or arm64]
  - 1.26 # [osx and not arm64]

MACOSX_DEPLOYMENT_TARGET:
  - 11.0 # [osx and not arm64]
  - 11.0 # [osx and arm64]
  #- 10.15 # [osx and not arm64]

c_compiler:
  - vs2022 # [win]
cxx_compiler:
  - vs2022 # [win]
cxx_compiler_version:
  - 15 # [linux]
c_compiler_version:
  - 15 # [linux]

c_stdlib:
  - sysroot # [linux]
c_stdlib_version:            # [linux]
  - 2.17
cdt_name:
  - cos7                  # [linux]

pin_run_as_build:
  python:
    min_pin: x.x.x
    max_pin: x.x.x
  ffmpeg:
    min_pin: x.x.x
    max_pin: x.x.x
    
channel_sources:
  - conda-forge
  - nodefaults
