name: CondaBuildLinux

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  GITHUB_WORKFLOW: CondaBuildUbuntu

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04"]
        solver: ["classic"]
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: 'recursive'
    - name: Cache conda
      uses: actions/cache@v4
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 1
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('.github/environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        environment-file: .github/environment.yml
        activate-environment: tracking
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        auto-activate-base: true
        auto-update-conda: true
    - name: Build
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}
      run: |
        echo "::group::Info"
        conda info
        conda list
        echo "::endgroup::"
        echo "::group::Fix Meta"
        cd $GITHUB_WORKSPACE/conda
        p=${GITHUB_REF##*/}
        sed -i -e '/^{% set git_tag =/ s+main+'$p'+g' meta.yaml
        sed -i -e 's/_cuda[0-9.]*/\*/g' -e 's/_cudnn/\*/g' -e 's/_cu[0-9.]*/\*/g' meta.yaml
        sed -i.bak 's|--index-url https://download.pytorch.org/whl/cu118||g' post-link.sh
        cat meta.yaml
        echo "::endgroup::"
        echo "::group::Build"
        conda update --all --override-channels -c conda-forge -y
        conda build . --override-channels -c conda-forge
        echo "::endgroup::"
        echo $CONDA_PREFIX
    - name: Test
      shell: bash -l {0}
      working-directory: ${{runner.workspace}}
      run: |
        echo "::group::Test"
        echo $CONDA_PREFIX
        conda create -y -n test --override-channels -c $CONDA_PREFIX/conda-bld/ -c conda-forge trex
        conda activate test
        pvinfo -opencv_ffmpeg_support
        pvinfo -opencv_opencl_support
        echo "::endgroup::"
        echo "::group::TestFunctions"
        conda install -y unzip
        cd $GITHUB_WORKSPACE/Application/Tests
        ./run_unix.bash
        echo "::endgroup::"
    - name: Upload failure artifacts (.csv, .npz, logs, html)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: linux-failure-artifacts
        path: |
          ${{ github.workspace }}/videos/corrected/data/*.csv
          ${{ github.workspace }}/videos/**/*.html
          ${{ github.workspace }}/videos/**/*.log
          ${{ github.workspace }}/videos/**/*.npz
        if-no-files-found: ignore
        retention-days: 7
